apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: app 
  template:
    metadata:
      labels:
        tier: app 
    spec:
      containers:
        - name: pet-clinic
          image: shebl22/petclinic:8cd8bb2970b3a81523a5b64d92cb25b0430617fa
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-cred
          ports:
            - containerPort: 5000
              