services:

  app:
    env_file:
      - dev.env
    depends_on:
      - db

  db:
    image: mysql:9.2
    container_name: mysql-db
    ports:
      - "3306:3306"
    env_file:
      - dev.secrets.env
    networks:
      - net
    volumes:
      - vol1:/var/lib/mysql

  


volumes:
  vol1:

networks:
  net:
