services:

  app:
    env_file:
      - prod.env
  db:
    image: postgres:17.5
    container_name: pg-db
    ports:
      - 5432 
    env_file:
      - prod.secrets.env

    networks:
      - net 
    
    volumes:
      - vol2:/var/lib/postgresql/data

volumes:
  vol2:

  