services:
  app:
    image: petclinic
    container_name: petclinic
    ports:
      - 5000:5000

    environment:
      - SERVER_PORT=5000
      - SERVER_SERVLET_CONTEXT_PATH=/app

    depends_on:
      - db
    networks:
      - net 

networks:
  net: 