configs:
  secret:
    argocdServerAdminPassword: "$2a$10$MVBkBkAxErFWaBpXA4Ltz.Kiwhcz0CkNmVZZgZPa/03JpykN50BVO"
  cm:
    timeout.reconciliation: 30s

server:
  service:
    type: NodePort
    nodePortHttp: 32080
    nodePortHttps: 32443

  metrics:
    enabled: true
    service:
      portName: metrics
      port: 8083
      targetPort: 8083

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

repoServer:
  metrics:
    enabled: true
    service:
      portName: metrics
      port: 8081
      targetPort: 8081

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

controller:
  metrics:
    enabled: true
    service:
      portName: metrics
      port: 8082
      targetPort: 8082

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 512Mi

dex:
  metrics:
    enabled: true
    service:
      portName: metrics
      port: 5558
      targetPort: 5558

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

extraObjects:
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: argocd-application-controller-metrics
        namespace: monitoring
        labels:
          release: my-kube-prometheus-stack
      spec:
        namespaceSelector:
          matchNames:
            - argocd
        selector:
          matchLabels:
            app.kubernetes.io/name: argocd-metrics
        endpoints:
          - port: metrics
            interval: 30s

    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: argocd-server-metrics
        namespace: monitoring
        labels:
          release: my-kube-prometheus-stack
      spec:
        namespaceSelector:
          matchNames:
            - argocd
        selector:
          matchLabels:
            app.kubernetes.io/name: argocd-server-metrics
        endpoints:
          - port: metrics
            interval: 30s
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: argocd-repo-server-metrics
        namespace: monitoring
        labels:
          release: my-kube-prometheus-stack
      spec:
        namespaceSelector:
          matchNames:
            - argocd
        selector:
          matchLabels:
            app.kubernetes.io/name: argocd-repo-server-metrics
        endpoints:
          - port: metrics
            interval: 30s
