apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: app 
  template:
    metadata:
      labels:
        tier: app 
    spec:
      containers:
        - name: pet-clinic
          image: shebl22/petclinic:v1
          envFrom:
            - configMapRef:
                name: app-cred
          ports:
            - containerPort: 5000
              
