apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  selector:
    matchLabels:
      tier: app 
  template:
    metadata:
      labels:
        tier: app 
    spec:
      containers:
        - name: pet-clinic
          image: shebl22/petclinic:09c39a5af096faf8819b38d8a8057ae60d8e198d
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: app-cred
          ports:
            - containerPort: 5000
              