apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
spec:
  selector:
    matchLabels:
      tier: db 
  template:
    metadata:
      labels:
        tier: db 
    spec:
      containers:
        - name: my
          image: mysql:9.2
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
          envFrom:
            - secretRef:
                name: db-cred
          
          ports:
            - containerPort: 3306
      volumes:
         - name: data 
           persistentVolumeClaim:
             claimName: pvc 