name: Petclinic pipelines
on: 
    workflow_dispatch: 
    push: 
      branches: 
        - 'main'
        - 'feature/*'
permissions:
      contents: write 
jobs: 

    Unit-testing:
        defaults:
          run:
            working-directory: pet-clinic
        runs-on: ubuntu-latest   

        steps:
        - name: checkout code
          uses: actions/checkout@v5
          with:
            path: pet-clinic
          

        - name: Installing Java
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin' 
            java-version: '21'
            cache: maven  

        - name: Run tests 
          run: mvn test

        - name: Uploading test results
          uses: actions/upload-artifact@v4
          with:
            name: JUnit Tests
            path: target/surefire-reports/*.xml


    Docker-build-push:
      
        runs-on: ubuntu-latest   

        defaults:
          run:
            working-directory: pet-clinic

        steps:

        - name: checkout code
          uses: actions/checkout@v5
          with:
            path: pet-clinic

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with: 
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/petclinic:${{github.sha}}  #pipeline_id

    Deploy:
    
        runs-on: ubuntu-latest
        needs: Docker-build-push
        steps:
            - name: checkout code
              uses: actions/checkout@v5
              # with:
              #   repository: abdelrahman-shebl/PetClinic-app
              #   token: ${{ secrets.GH_PAT}}

            - name: Update K8s Manifests
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '{'
                tokenSuffix: '}'
                files: '["K8s/Deployments/app-deployment.yml"]'
              env:
                IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/petclinic:${{github.sha}} 

            - name: push to the remote repository
              uses: stefanzweifel/git-auto-commit-action@v6
              with: 

                commit_message: "Update image to ${{ github.sha }}"
              env:
                GITHUB_TOKEN: ${{ secrets.GH_PAT }}