name: Petclinic pipelines
on: 
    workflow_dispatch: 
    push: 
      branches: 
        - 'main'
        - 'feature/*'
permissions:
      contents: write 
      
jobs: 
    Unit-testing:
        defaults:
          run:
            working-directory: pet-clinic
        runs-on: ubuntu-latest   

        steps:
        - name: checkout code
          uses: actions/checkout@v5

        - name: Installing Java
          uses: actions/setup-java@v5
          with:
            distribution: 'temurin' 
            java-version: '21'
            cache: maven  

        - name: Run tests 
          run: mvn test -Dtest=!PostgresIntegrationTests

        - name: Uploading test results
          uses: actions/upload-artifact@v4
          with:
            name: JUnit Tests
            path: |
              pet-clinic/target/surefire-reports/*.xml
              pet-clinic/target/failsafe-reports/*.xml

        - name: Publish test results
          uses: mikepenz/action-junit-report@v4
          if: always() 
          with:
            report_paths: |
              pet-clinic/target/surefire-reports/*.xml
              pet-clinic/target/failsafe-reports/*.xml


    Docker-build:

        needs:  Unit-testing
        outputs: 
          Image_tag: ${{steps.build-image.outputs.tag}}

        runs-on: ubuntu-latest   
        steps:

        - name: checkout code
          uses: actions/checkout@v5

        - name: Set Docker Image Tag
          id: build-image
          run: |
            echo "tag=${{ vars.DOCKERHUB_USERNAME }}/petclinic:${{ github.sha}}" >> $GITHUB_OUTPUT


        - name: Build 
          uses: docker/build-push-action@v6
          with: 
            context: ./pet-clinic         
            file: ./pet-clinic/Dockerfile
            push: false
            tags: ${{ steps.build-image.outputs.tag }}  #pipeline_id

    Trivy-scan:
      runs-on: ubuntu-latest
      needs: Docker-build
      steps:
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.28.0
          with:
            image-ref: ${{needs.Docker-build.outputs.Image_tag}}
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
          continue-on-error: true
    
    
    Docker-push:

        needs:  Trivy-scan

        runs-on: ubuntu-latest   
        steps:
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: push 
            uses: docker/build-push-action@v6
            with: 
              context: ./pet-clinic         
              file: ./pet-clinic/Dockerfile
              push: true
              tags: ${{needs.Docker-build.outputs.Image_tag}}


    Deploy:
    
        runs-on: ubuntu-latest
        needs: Docker-push
        steps:
            - name: checkout code
              uses: actions/checkout@v5

            - name: Update K8s Manifests
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '{'
                tokenSuffix: '}'
                files: '["K8s/Deployments/app-deployment.yml"]'
              env:
                IMAGE: ${{needs.Docker-build.outputs.Image_tag}}

            - name: push to the remote repository
              uses: stefanzweifel/git-auto-commit-action@v6
              with: 

                commit_message: "Update image to ${{ github.sha }}"
              env:
                GITHUB_TOKEN: ${{ secrets.GH_PAT }}