name: Petclinic pipelines
on: 
    workflow_dispatch: 
    push: 
      branches: 
        - 'feature/*'
jobs:
    Docker-build-push:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v5
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/petclinic:${{github.sha}} 

    Deploy:
        runs-on: ubuntu-latest
        needs: Docker-build-push
        steps:
            - name: checkout code
              uses: actions/checkout@v5
              with:
                repository: abdelrahman-shebl/PetClinic-app
                token: ${{ secrets.GH_PAT}}

            - name: Update K8s Manifests
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '{'
                tokenSuffix: '}'
                files: '["K8s/Deployments/app-deplotment.yml"]'
              env:
                IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/petclinic:${{github.sha}} 

            - uses: stefanzweifel/git-auto-commit-action@v6
              with:

                commit_message: "Update image to ${{ github.sha }}"
