name: Petclinic pipelines
on: 
    workflow_dispatch: 
    push: 
      branches: 
        - 'main'
        - 'feature/*' 
      
jobs: 
    # Unit-testing:
    #     permissions: 
    #       contents: read
    #       checks: write
    #     defaults:
    #       run:
    #         working-directory: CI/pet-clinic
    #     runs-on: ubuntu-latest   

    #     steps:
    #     - name: checkout code
    #       uses: actions/checkout@v5

    #     - name: Installing Java
    #       uses: actions/setup-java@v5
    #       with:
    #         distribution: 'temurin' 
    #         java-version: '21'
    #         cache: maven  

    #     - name: Run tests 
    #       run: mvn test -Dtest=!PostgresIntegrationTests

    #     - name: Uploading test results
    #       uses: actions/upload-artifact@v4
    #       with:
    #         name: JUnit Tests
    #         path: |
    #           CI/pet-clinic/target/surefire-reports/*.xml
    #           CI/pet-clinic/target/failsafe-reports/*.xml

    #     - name: Publish test results
    #       uses: mikepenz/action-junit-report@v4
    #       if: always()
    #       continue-on-error: true
    #       with:
    #         report_paths: |
    #           CI/pet-clinic/target/surefire-reports/*.xml
    #           CI/pet-clinic/target/failsafe-reports/*.xml
    #         check_name: |
    #           Surefire
    #           Failsafe
              
    # build-scan-push:
    #   runs-on: ubuntu-latest
    #   needs: Unit-testing
    #   steps:
    #     - uses: actions/checkout@v5

    #     - name: Login Docker
    #       uses: docker/login-action@v3
    #       with:
    #         username: ${{ vars.DOCKERHUB_USERNAME }}
    #         password: ${{ secrets.DOCKERHUB_TOKEN }}

    #     - name: Build Docker image
    #       uses: docker/build-push-action@v6
    #       with:
    #         context: CI/pet-clinic
    #         push: false
    #         tags: ${{ vars.DOCKERHUB_USERNAME }}/petclinic:${{ github.sha }}

    #     - name: Scan Docker image with Trivy
    #       uses: aquasecurity/trivy-action@0.28.0
    #       with:
    #         image-ref: ${{ vars.DOCKERHUB_USERNAME }}/petclinic:${{ github.sha }}
    #         format: table
    #         ignore-unfixed: true
    #         vuln-type: os,library
    #         severity: CRITICAL,HIGH
    #       continue-on-error: true

    #     - name: Push Docker image
    #       uses: docker/build-push-action@v6
    #       with:
    #         context: CI/pet-clinic
    #         push: true
    #         tags: ${{ vars.DOCKERHUB_USERNAME }}/petclinic:${{ github.sha }}


    # Deploy:
    
    #     runs-on: ubuntu-latest
    #     permissions: 
    #       contents: write
    #     needs: build-scan-push
    #     steps:
    #         - name: checkout code
    #           uses: actions/checkout@v5

    #         - name: Update K8s Manifests
    #           uses: cschleiden/replace-tokens@v1
    #           with:
    #             tokenPrefix: '{'
    #             tokenSuffix: '}'
    #             files: '["CI/K8s/Deployments/app-deployment.yml"]'
    #           env:
    #             IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/petclinic:${{github.sha}} 

    #         - name: push to the remote repository
    #           uses: stefanzweifel/git-auto-commit-action@v6
    #           with: 

    #             commit_message: "Update image to ${{ github.sha }}"
    #           env:
    #             GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    Slack-Gmail-Notifications:
      # needs: Deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3 
        - name: Send Slack Notification
          if: always() 
          uses: 8398a7/action-slack@v3
          with:
            status: ${{ job.status }}
            author_name: ${{ github.actor }}
            fields: workflow,job,commit,repo,ref
            custom_payload: |
              {
                "attachments": [
                  {
                    "color": "${{ job.status == 'success' && 'good' || job.status == 'failure' && 'danger' || job.status == 'cancelled' && 'warning' }}",
                    "title": "Workflow ${{ github.workflow }}",
                    "text": "Job: ${{ github.job }}\nBranch: ${{ github.ref }}\nCommit: ${{ github.sha }}\nAuthor: ${{ github.actor }}\nStatus: ${{ job.status }}",
                    "footer": "GitHub Actions",
                    "ts": $(date +%s)
                  }
                ]
              }
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


        - name: Send Gmail Notification
          uses: Raghul-M/gmail-sender-action@v1
          with:
            sender_email: ${{ secrets.GMAIL_USERNAME }}
            app_password: ${{ secrets.GMAIL_APP_PASSWORD }}
            receiver_emails: "recipient1@example.com,recipient2@example.com"
            template_path: ".github/email-template.html"
            subject: "Workflow ${{ github.workflow }} Status: ${{ job.status }}"