name: Petclinic pipelines
on: 
    workflow_dispatch: 
    push: 
      branches: 
        - main
        - 'feature/*'

permissions:
  contents: write 
jobs:
    Docker-build-push:
        runs-on: ubuntu-latest
        outputs:
          image_tag: ${{ steps.tag.outputs.image_tag }}
        steps:
        - name: checkout code
          uses: actions/checkout@v5
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/petclinic:${{github.sha}} 


        - name: Set image tag global
          id: tag
          run: echo "image_tag=${{ vars.DOCKERHUB_USERNAME }}/petclinic:${{github.sha}}"  >> $GITHUB_OUTPUT
    Deploy:
        runs-on: ubuntu-latest
        needs: Docker-build-push
        steps:
            - name: checkout code
              uses: actions/checkout@v5
              with:
                repository: abdelrahman-shebl/PetClinic-app
                token: ${{ secrets.GH_PAT}}
            
            - name: Update K8s Manifests
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '{'
                tokenSuffix: '}'
                files: '["K8s/Deployments/app-deplotment.yml"]'
              env:
                IMAGE: ${{ needs.Docker-build-push.outputs.image_tag }}

            - uses: stefanzweifel/git-auto-commit-action@v6
              with:

                commit_message: "Update image to ${{ needs.Docker-build-push.outputs.image_tag }}"
